config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'order/is_paid/:id', to: 'orders#is_paid', as: 'order_is_paid'
  resources :line_items
  resources :carts
  resources :charges

  resources :merchants, only: [:show]
  get 'product/:id', to: 'products#show', as: 'product'
  delete 'product/:id', to: 'products#destroy', as: 'product_destroy'
  get 'products/new_arrivals', to: 'products#new_arrivals'

  get 'products/most_populars', to: 'products#most_populars'

  get 'products/official_brands', to: 'products#official_brands'

  root 'home#index'

  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(path: :admin)
  ActiveAdmin.routes(self)
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_one :purchase
  validates :name, :address,  presence: true
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  def total_price
    line_items.to_a.sum(&:total_price)
  end
  def recent(user_id)
    User.find(user_id).line_items.joins(:order)
        .select("order_id as id,orders.name as buyer, orders.address,orders.created_at")
        .where("orders.status = 1").group("order_id")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:edit, :update, :destroy, :show]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    respond_to do |format|
      @is_paid = (@order.status == 1)
      # @order
      if @is_paid
        email_to = 'riansyah@41studio.com' #TODO: di order nanti tambahkan email pengirim
        UserMailer.purchase_mail(@order,email_to).deliver_later
        format.html { render :is_paid }
      elsif
        format.html { render :show }
      end
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to order_path(@order), notice:
            'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address)
    end
    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to carts_path, notice: 'Your cart is empty'
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_detail_order.html.erb
<h1 align='center'>Orders</h1>
<p id="notice"><%= notice %></p>
<table class="table" >
  <tbody>
    <tr>
      <th>INV20181010101210</th>
    </tr>
    <tr>
      <td rowspan="2">
        <b>Item</b>
      </td>
      <td>
          <table>
            <% @order.line_items.each do |item| %>
              <tr>
                <td><%= item.product.title %></td>
                <td><%= item.quantity %>&times;</td>
                <td><%= number_to_currency(item.product.price) %></td>
                <td class="item_price"><%= number_to_currency(item.total_price) %></td>
                <% unless @is_paid %>
                  <td><%= link_to 'Destroy', line_item_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </tr>
            <% end %>

            <tr class="total_line">
              <td colspan="2"></td>
              <th >Total</th>
              <th ><%= number_to_currency(@order.total_price) %></th>
            </tr>
          </table>
      </td>

    </tr>
    <tr>
      <td>
        <p>
          <strong>Name:</strong>
          <%= @order.name %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= @order.address %>
        </p>


        <%= link_to 'Edit', edit_order_path(@order) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :order_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :order_address %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/is_paid.html.erb
<br>
<div class="new_arrivals">
  <div class="container alert-success">

    <p>Thank you, your order has been placed
    We've sent you an e-mail confirmation</p>
    <p> Your orders will be delivered to <b><%= @order.address %></b>

       Estimated delivery : <b>10-03-2018</b>
    Review your order
    </p>

  </div>
  <div class="container">
    <%= button_to "continue shopping", root_path, :method => "get" %>
  </div>
  <div class="container">
    <%= render "detail_order" %>







  </div>
</div>

app/views/orders/new.html.erb
<div class="depot_form">

  <fieldset>

    <legend>Please Enter Your Details</legend>

    <%= render 'form', order: @order %>

  </fieldset>
</div>

app/views/orders/receipt.pdf.erb
<h1>Pembayaran anda sukses</h1>

<div class="">
  <p>
    Hi <%= @order.name %>, silahkan tunggu pengiriman barang, berikut detail pembelian anda :
  </p>
  <table>
    <% @order.line_items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= item.quantity %>&times;</td>
        <td><%= number_to_currency(item.product.price) %></td>
        <td class="item_price"><%= number_to_currency(item.total_price) %></td>
      </tr>
    <% end %>

    <tr class="total_line">
      <td colspan="2"></td>
      <th >Total</th>
      <th ><%= number_to_currency(@order.total_price) %></th>
    </tr>
  </table>
</div>

app/views/orders/show.html.erb
<br>
<div class="new_arrivals">
  <div class="container">
    <%= render "detail_order" %>

    <div align='center'>
      <%= form_tag charges_path, id:'chargeForm' do %>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>

      <!-- use credit card number 4242 4242 4242 4242 , any three digit CVC and any expiry date-->
      <script src="https://checkout.stripe.com/checkout.js"></script>
      <%= hidden_field_tag 'emailUser', current_user.email %>
      <%= hidden_field_tag 'stripeToken' %>
      <%= hidden_field_tag 'stripeEmail' %>
      <%= hidden_field_tag 'amount', (@order.total_price * 100).to_i %>
      <%= hidden_field_tag 'orderId', @order.id %>
      <button id="btn-buy" type="button" class="btn btn-primary">
        Pay With Card
      </button>
      <script type="text/javascript">
        var handler = StripeCheckout.configure({
          key: '<%= Rails.configuration.stripe[:publishable_key] %>',
          token: function (token, arg) {
            document.getElementById("stripeToken").value = token.id;
            document.getElementById("stripeEmail").value = token.email;
            document.getElementById("chargeForm").submit();
          }
        });
        // membuka popup dialog, ketiga paramater name,description, amount harus diisi
        document.getElementById("btn-buy").addEventListener('click', function (e) {
          handler.open({name: 'Beliyuk', description: 'Buy these thing',email: document.getElementById("emailUser").value, amount: document.getElementById("amount").value});
          // amount in cent
          e.preventDefault();
        });
      </script>
      <% end %>
    </div>



</div>
</div>