config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'order/is_paid/:id', to: 'orders#is_paid', as: 'order_is_paid'
  resources :line_items
  resources :carts
  resources :charges

  resources :merchants, only: [:show]
  get 'product/:id', to: 'products#show', as: 'product'
  delete 'product/:id', to: 'products#destroy', as: 'product_destroy'
  get 'products/new_arrivals', to: 'products#new_arrivals'

  get 'products/most_populars', to: 'products#most_populars'

  get 'products/official_brands', to: 'products#official_brands'

  root 'home#index'

  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(path: :admin)
  ActiveAdmin.routes(self)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :destroy, Product do |product|
        product.merchant.user == user
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
    # line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart
  def total_price
    product.price * quantity
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  has_one :user
  has_many :products

  def get_name(user_id)
    User.find(user_id).merchant.name
  end

  def get_id(user_id)
    User.find(user_id).merchant.id
  end

  def our_product(merchant_id)
    Merchant.find(merchant_id).products.order(:created_at)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_one :purchase
  validates :name, :address,  presence: true
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  def total_price
    line_items.to_a.sum(&:total_price)
  end
  def recent(user_id)
    User.find(user_id).line_items.joins(:order)
        .select("order_id as id,orders.name as buyer, orders.address,orders.created_at")
        .where("orders.status = 1").group("order_id")
  end
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  has_many :line_items
  has_many :product_images
  accepts_nested_attributes_for :product_images
  has_many :orders, through: :line_items
  belongs_to :merchant
  before_destroy :ensure_not_referenced_by_any_line_item
  def my_product?(product_id,user_id)
    User.find(user_id).merchant.products.find(product_id).blank?
    rescue ActiveRecord::RecordNotFound
      true
  end
  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image_url, ImageUploader

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :order
  belongs_to :user
  def detail_for_buyer(user_id,purchase_id)
    User.find(user_id).purchases.joins(order: {line_items: :product})
      .select("orders.id, purchases.amount,
        GROUP_CONCAT(products.title ) as product_name,
        GROUP_CONCAT( '( '|| products.price || '*' || line_items.quantity || ' )' ) as price,
        purchases.card,
        orders.created_at,
        orders.updated_at
      ")
      .where("purchases.id = #{purchase_id}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # belongs_to berarti merchant_id ada di User
  # di buat opsi true, agar merchant ga harus dibutuhkan saat di save
  belongs_to :merchant,optional: true
  has_many :purchases
  has_many :products, through: :merchant
  has_many :line_items, through: :products
  has_many :orders, through: :line_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def as_merchant(user_id)
    User.joins(:merchant)
        .select("merchants.id, merchants.name,description,address,merchants.image_url")
        .where("users.id = #{user_id}")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.order(:created_at).page(params[:page])

    @header_page = "New Arrival"

  end
end

app/controllers/merchants_controller.rb
class MerchantsController < InheritedResources::Base
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @products = Merchant.new.our_product(params[:id]).page(params[:page])
    @merchant = Merchant.find(params[:id])
  end
  private

    def merchant_params
      params.require(:merchant).permit(:name, :image_url, :description, :products_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_to_cart_btn(product_id)
     if user_signed_in? && Product.new.my_product?(product_id,current_user.id)
         button_to 'Add to Cart', line_items_path(product_id: product_id), remote: true
     elsif !user_signed_in?
       content_tag(:b, "sign in to buy")
     end
  end
  def get_link_merchant(user_id)
    begin
      content_link  = link_to Merchant.new.get_name(current_user.id),customers_merchants_path, method: 'get'
      content_tag(:li , content_link)
    rescue
    end
  end

  def display_merchant(merchant_image)
    if merchant_image.file.exists?
      image_tag merchant_image
    else
      image_tag 'default-merchant.png'
    end
  end

  def display_product(product_image)
    if product_image.file.exists?
      image_tag product_image
    else
      image_tag 'default-product.jpg'
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/merchants/_form.html.erb
<br>
<%= form_with(model: merchant, local: true) do |form| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :merchant_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.file_field :image_url, id: :merchant_image_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :merchant_description %>
  </div>

  <div class="field">
    <%= form.label :products_id %>
    <%= form.text_field :products_id, id: :merchant_products_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Description</th>
      <th>Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.image_url %></td>
        <td><%= merchant.description %></td>
        <td><%= merchant.products %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<div class="container single_product_container">
  <div class="row">
    <div class="col-lg-4">
      <div class="single_product_pics">
        <div class="row">
          <div class="col-lg-3 image_col order-lg-2 order-1">
            <div class="single_product_image">
              <%= display_merchant(@merchant.image_url) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="product_details">
        <div class="">
          <h2><%= @merchant.name %></h2>
          <p><%= @merchant.description %>
          </p>
        </div>

      </div>

    </div>
  </div>


</div>
<div style="margin-top : -400px">
  <%= render(partial: "shared/list_product") %>

</div>