config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'order/is_paid/:id', to: 'orders#is_paid', as: 'order_is_paid'
  resources :line_items
  resources :carts
  resources :charges

  resources :merchants, only: [:show]
  get 'product/:id', to: 'products#show', as: 'product'
  delete 'product/:id', to: 'products#destroy', as: 'product_destroy'
  get 'products/new_arrivals', to: 'products#new_arrivals'

  get 'products/most_populars', to: 'products#most_populars'

  get 'products/official_brands', to: 'products#official_brands'

  root 'home#index'

  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(path: :admin)
  ActiveAdmin.routes(self)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :destroy, Product do |product|
        product.merchant.user == user
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
    # line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart
  def total_price
    product.price * quantity
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  has_one :user
  has_many :products

  def get_name(user_id)
    User.find(user_id).merchant.name
  end

  def get_id(user_id)
    User.find(user_id).merchant.id
  end

  def our_product(merchant_id)
    Merchant.find(merchant_id).products.order(:created_at)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_one :purchase
  validates :name, :address,  presence: true
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  def total_price
    line_items.to_a.sum(&:total_price)
  end
  def recent(user_id)
    User.find(user_id).line_items.joins(:order)
        .select("order_id as id,orders.name as buyer, orders.address,orders.created_at")
        .where("orders.status = 1").group("order_id")
  end
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  has_many :line_items
  has_many :product_images
  accepts_nested_attributes_for :product_images
  has_many :orders, through: :line_items
  belongs_to :merchant
  before_destroy :ensure_not_referenced_by_any_line_item
  def my_product?(product_id,user_id)
    User.find(user_id).merchant.products.find(product_id).blank?
    rescue ActiveRecord::RecordNotFound
      true
  end
  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image_url, ImageUploader

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :order
  belongs_to :user
  def detail_for_buyer(user_id,purchase_id)
    User.find(user_id).purchases.joins(order: {line_items: :product})
      .select("orders.id, purchases.amount,
        GROUP_CONCAT(products.title ) as product_name,
        GROUP_CONCAT( '( '|| products.price || '*' || line_items.quantity || ' )' ) as price,
        purchases.card,
        orders.created_at,
        orders.updated_at
      ")
      .where("purchases.id = #{purchase_id}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # belongs_to berarti merchant_id ada di User
  # di buat opsi true, agar merchant ga harus dibutuhkan saat di save
  belongs_to :merchant,optional: true
  has_many :purchases
  has_many :products, through: :merchant
  has_many :line_items, through: :products
  has_many :orders, through: :line_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def as_merchant(user_id)
    User.joins(:merchant)
        .select("merchants.id, merchants.name,description,address,merchants.image_url")
        .where("users.id = #{user_id}")
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeliYuk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application',params[:controller] , media: 'all',
        'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="super_container">

    	<!-- Header -->

    	<header class="header trans_300">

    		<!-- Top Navigation -->

    		<div class="top_nav">
    			<div class="container">
    				<div class="row">
    					<div class="col-md-6">
    						<div class="top_nav_left">free shipping on all u.s orders over $50</div>
    					</div>
    					<div class="col-md-6 text-right">
    						<div class="top_nav_right">
    							<ul class="top_nav_menu">

    								<li class="account">

    										<% if user_signed_in? %>
    												<a href="#">
    													<%= current_user.email %>
    													<i class="fa fa-angle-down"></i>
    												</a>
    												<ul class="account_selection">
    													<li><%= link_to 'Dashboard', customers_dashboard_path, method: 'get' %> </li>

    													<li><%= get_link_merchant(current_user.id) %> </li>
    													<li><%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %> </li>
    												</ul>
    										<% else %>
    											<%= link_to 'Sign In', new_user_session_path %>
    								</li>
    								<li class="account">
    									<%= link_to 'Sign Up', new_user_registration_path %>
    								</li>
    								<% end %>
    							</ul>
    						</div>
    					</div>
    				</div>
    			</div>
    		</div>

    		<!-- Main Navigation -->

    		<div class="main_nav_container">
    			<div class="container">
    				<div class="row">
    					<div class="col-lg-12 text-right">
    						<div class="logo_container">
                  <%= link_to "BeliYuk", root_path %>
    						</div>
    						<nav class="navbar">
    							<ul class="navbar_menu">

                    <li><%= link_to 'new arrival', products_new_arrivals_path %> </li>
                    <li><%= link_to 'most popular', products_most_populars_path %> </li>
                    <li><%= link_to 'official brand', products_official_brands_path %> </li>
                  </ul>
    							<ul class="navbar_user">
    								<!-- <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li> -->
    								<li class="checkout">

    									<a href="<%= carts_path %>">
    										<i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        <% if @cart %>
      										<span id="checkout_items" class="checkout_items">
                              <%= @cart.line_items.length %>
                          </span>
                        <% end %>
    									</a>
    								</li>
    							</ul>
    							<div class="hamburger_container">
    								<i class="fa fa-bars" aria-hidden="true"></i>
    							</div>
    						</nav>
    					</div>
    				</div>
    			</div>
    		</div>


    	</header>
<br><br><br><br><br><br>
    <%= yield %>

    	<!-- Footer -->

    	<footer class="footer">
    		<div class="container">
    			<div class="row">
    				<div class="col-lg-6">
    					<div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
    						<ul class="footer_nav">
    							<li><a href="#">Blog</a></li>
    							<li><a href="#">FAQs</a></li>
    							<li><a href="contact.html">Contact us</a></li>
    						</ul>
    					</div>
    				</div>
    				<div class="col-lg-6">
    					<div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
    						<ul>
    							<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
    							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
    							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
    							<li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
    							<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
    						</ul>
    					</div>
    				</div>
    			</div>
    			<div class="row">
    				<div class="col-lg-12">
    					<div class="footer_nav_container">
    						<div class="cr">©2018 All Rights Reserverd. This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a></div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</footer>

    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_list_product.html.erb
	<div class="new_arrivals">

		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_title new_arrivals_title">
						<h2><%= @header_page %> </h2>
					</div>
				</div>
			</div>

			<div class="row">
				<%= paginate @products %>
			</div>
			<div class="row">

				<div class="col">
				<!-- isotop yang memperbaiki posisinya -->
					<div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>
						<% @products.each do |product| %>
							<div class="product-item" style="">

									<div class="product_image">
										<%= display_product product.product_images.first.image_url%>
									</div>
										<% if can? :destroy, product%>
											<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center">
												<span class="delete_bubble"> <%= link_to 'delete', product, method: :delete,
															data: { confirm: 'Are you sure?' } %>
												</span>
											</div>
										<% end %>
									<div class="product_info">
										<h6 class="product_name">
											<%= link_to product.title, product %> <br>
											<%= link_to product.merchant.name, product.merchant %>
										</h6>
										<div class="product_price"><%= number_to_currency(product.price) %></div>
									</div>
								<div align='center' class="add_to_cart_button">
									<%= add_to_cart_btn(product.id) %>

								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>

		</div>
	</div>
    <%= javascript_include_tag 'isotope.pkgd.min'%>